import { describe, test, expect } from 'vitest';
import formatDate from "../../src/utils/dateFormatter";

//  Tests below generated by co-pilot

describe('formatDate', () => {
  it('should correctly format a date', () => {
    const date = new Date(2022, 0, 1, 12); // January 1, 2022 at 12:00
    const result = formatDate(date);
    expect(result).toEqual({
      year: 2022,
      month: 1,
      monthName: 'January',
      day: 1,
      hour: 12,
      dayOfWeek: 'Saturday',
    });
  });

  it('should correctly format a different date', () => {
    const date = new Date(2023, 11, 31, 23); // December 31, 2023 at 23:00
    const result = formatDate(date);
    expect(result).toEqual({
      year: 2023,
      month: 12,
      monthName: 'December',
      day: 31,
      hour: 23,
      dayOfWeek: 'Sunday',
    });
  });
});